
export const enum ThingKind {
  artifact = 'artifact',
  pickup = 'pickup',
  weapon = 'weapon',
  monster = 'monster',
  obstacle = 'obstacle'
}

export interface ThingType {
  id: number;
  radius: number;
  sprite?: string;
  sequence?: string;
  description: string;
  kind?: ThingKind;
  isFloater?: boolean;
}

export const thingTypes: Array<ThingType> = [
  { id: 1, radius: 16, sprite: 'PLAY', description: 'Player 1 start' },
  { id: 2, radius: 16, sprite: 'PLAY', description: 'Player 2 start' },
  { id: 3, radius: 16, sprite: 'PLAY', description: 'Player 3 start' },
  { id: 4, radius: 16, sprite: 'PLAY', description: 'Player 4 start' },
  { id: 5, radius: 20, sprite: 'BKEY', sequence: 'AB', kind: ThingKind.pickup, description: 'Blue keycard' },
  { id: 6, radius: 20, sprite: 'YKEY', sequence: 'AB', kind: ThingKind.pickup, description: 'Yellow keycard' },
  { id: 7, radius: 128, sprite: 'SPID', kind: ThingKind.monster, description: 'Spider Mastermind' },
  { id: 8, radius: 20, sprite: 'BPAK', sequence: 'A', kind: ThingKind.pickup, description: 'Backpack' },
  { id: 9, radius: 20, sprite: 'SPOS', kind: ThingKind.monster, description: 'Former Human Sergeant' },
  { id: 10, radius: 16, sprite: 'PLAY', sequence: 'W'	, description: 'Bloody mess' },
  { id: 11, radius: 20, description: 'Deathmatch start' },
  { id: 12, radius: 16, sprite: 'PLAY', sequence: 'W'	, description: 'Bloody mess' },
  { id: 13, radius: 20, sprite: 'RKEY', sequence: 'AB', kind: ThingKind.pickup, description: 'Red keycard' },
  { id: 14, radius: 20, description: 'Teleport landing' },
  { id: 15, radius: 16, sprite: 'PLAY', sequence: 'N', description: 'Dead player' },
  { id: 16, radius: 40, sprite: 'CYBR', kind: ThingKind.monster, description: 'Cyberdemon' },
  { id: 17, radius: 20, sprite: 'CELP', sequence: 'A', kind: ThingKind.pickup, description: 'Cell charge pack' },
  { id: 18, radius: 20, sprite: 'POSS', sequence: 'L', description: 'Dead former human' },
  { id: 19, radius: 20, sprite: 'SPOS', sequence: 'L', description: 'Dead former sergeant' },
  { id: 20, radius: 20, sprite: 'TROO', sequence: 'M', description: 'Dead imp' },
  { id: 21, radius: 30, sprite: 'SARG', sequence: 'N', description: 'Dead demon' },
  { id: 22, radius: 31, sprite: 'HEAD', sequence: 'L', description: 'Dead cacodemon' },
  { id: 23, radius: 16, sprite: 'SKUL', sequence: 'K', description: 'Dead lost soul (invisible)' },
  { id: 24, radius: 16, sprite: 'POL5', sequence: 'A', description: 'Pool of blood and flesh' },
  { id: 25, radius: 16, sprite: 'POL1', sequence: 'A', kind: ThingKind.obstacle, description: 'Impaled human' },
  { id: 26, radius: 16, sprite: 'POL6', sequence: 'AB', kind: ThingKind.obstacle, description: 'Twitching impaled human' },
  { id: 27, radius: 16, sprite: 'POL4', sequence: 'A', kind: ThingKind.obstacle, description: 'Skull on a pole' },
  { id: 28, radius: 16, sprite: 'POL2', sequence: 'A', kind: ThingKind.obstacle, description: 'Five skulls "shish kebab"' },
  { id: 29, radius: 16, sprite: 'POL3', sequence: 'AB', kind: ThingKind.obstacle, description: 'Pile of skulls and candles' },
  { id: 30, radius: 16, sprite: 'COL1', sequence: 'A', kind: ThingKind.obstacle, description: 'Tall green pillar' },
  { id: 31, radius: 16, sprite: 'COL2', sequence: 'A', kind: ThingKind.obstacle, description: 'Short green pillar' },
  { id: 32, radius: 16, sprite: 'COL3', sequence: 'A', kind: ThingKind.obstacle, description: 'Tall red pillar' },
  { id: 33, radius: 16, sprite: 'COL4', sequence: 'A', kind: ThingKind.obstacle, description: 'Short red pillar' },
  { id: 34, radius: 16, sprite: 'CAND', sequence: 'A'	, description: 'Candle' },
  { id: 35, radius: 16, sprite: 'CBRA', sequence: 'A', kind: ThingKind.obstacle, description: 'Candelabra' },
  { id: 36, radius: 16, sprite: 'COL5', sequence: 'AB', kind: ThingKind.obstacle, description: 'Short green pillar with beating heart' },
  { id: 37, radius: 16, sprite: 'COL6', sequence: 'A', kind: ThingKind.obstacle, description: 'Short red pillar with skull' },
  { id: 38, radius: 20, sprite: 'RSKU', sequence: 'AB', kind: ThingKind.pickup, description: 'Red skull key' },
  { id: 39, radius: 20, sprite: 'YSKU', sequence: 'AB', kind: ThingKind.pickup, description: 'Yellow skull key' },
  { id: 40, radius: 20, sprite: 'BSKU', sequence: 'AB', kind: ThingKind.pickup, description: 'Blue skull key' },
  { id: 41, radius: 16, sprite: 'CEYE', sequence: 'ABCB', kind: ThingKind.obstacle, description: 'Evil eye' },
  { id: 42, radius: 16, sprite: 'FSKU', sequence: 'ABC', kind: ThingKind.obstacle, description: 'Floating skull' },
  { id: 43, radius: 16, sprite: 'TRE1', sequence: 'A', kind: ThingKind.obstacle, description: 'Burnt tree' },
  { id: 44, radius: 16, sprite: 'TBLU', sequence: 'ABCD', kind: ThingKind.obstacle, description: 'Tall blue firestick' },
  { id: 45, radius: 16, sprite: 'TGRN', sequence: 'ABCD', kind: ThingKind.obstacle, description: 'Tall green firestick' },
  { id: 46, radius: 16, sprite: 'TRED', sequence: 'ABCD', kind: ThingKind.obstacle, description: 'Tall red firestick' },
  { id: 47, radius: 16, sprite: 'SMIT', sequence: 'A', kind: ThingKind.obstacle, description: 'Stalagmite' },
  { id: 48, radius: 16, sprite: 'ELEC', sequence: 'A', kind: ThingKind.obstacle, description: 'Tall techno pillar' },
  { id: 49, radius: 16, sprite: 'GOR1', sequence: 'ABCB', kind: ThingKind.obstacle, isFloater: true, description: 'Hanging victim, twitching' },
  { id: 50, radius: 16, sprite: 'GOR2', sequence: 'A', kind: ThingKind.obstacle, isFloater: true, description: 'Hanging victim, arms out' },
  { id: 51, radius: 16, sprite: 'GOR3', sequence: 'A', kind: ThingKind.obstacle, isFloater: true, description: 'Hanging victim, one-legged' },
  { id: 52, radius: 16, sprite: 'GOR4', sequence: 'A', kind: ThingKind.obstacle, isFloater: true, description: 'Hanging pair of legs' },
  { id: 53, radius: 16, sprite: 'GOR5', sequence: 'A', kind: ThingKind.obstacle, isFloater: true, description: 'Hanging leg' },
  { id: 54, radius: 32, sprite: 'TRE2', sequence: 'A', kind: ThingKind.obstacle, description: 'Large brown tree' },
  { id: 55, radius: 16, sprite: 'SMBT', sequence: 'ABCD', kind: ThingKind.obstacle, description: 'Short blue firestick' },
  { id: 56, radius: 16, sprite: 'SMGT', sequence: 'ABCD', kind: ThingKind.obstacle, description: 'Short green firestick' },
  { id: 57, radius: 16, sprite: 'SMRT', sequence: 'ABCD', kind: ThingKind.obstacle, description: 'Short red firestick' },
  { id: 58, radius: 30, sprite: 'SARG', kind: ThingKind.monster, description: 'Spectre' },
  { id: 59, radius: 16, sprite: 'GOR2', sequence: 'A', isFloater: true, description: 'Hanging victim, arms out' },
  { id: 60, radius: 16, sprite: 'GOR4', sequence: 'A', isFloater: true, description: 'Hanging pair of legs' },
  { id: 61, radius: 16, sprite: 'GOR3', sequence: 'A', isFloater: true, description: 'Hanging victim, one-legged' },
  { id: 62, radius: 16, sprite: 'GOR5', sequence: 'A', isFloater: true, description: 'Hanging leg' },
  { id: 63, radius: 16, sprite: 'GOR1', sequence: 'ABCB', isFloater: true, description: 'Hanging victim, twitching' },
  { id: 64, radius: 20, sprite: 'VILE', kind: ThingKind.monster, description: 'Arch-Vile' },
  { id: 65, radius: 20, sprite: 'CPOS', kind: ThingKind.monster, description: 'Chaingunner' },
  { id: 66, radius: 20, sprite: 'SKEL', kind: ThingKind.monster, description: 'Revenant' },
  { id: 67, radius: 48, sprite: 'FATT', kind: ThingKind.monster, description: 'Mancubus' },
  { id: 68, radius: 64, sprite: 'BSPI', kind: ThingKind.monster, description: 'Arachnotron' },
  { id: 69, radius: 24, sprite: 'BOS2', kind: ThingKind.monster, description: 'Hell Knight' },
  { id: 70, radius: 10, sprite: 'FCAN', sequence: 'ABC', kind: ThingKind.obstacle, description: 'Burning barrel' },
  { id: 71, radius: 31, sprite: 'PAIN', kind: ThingKind.monster, isFloater: true, description: 'Pain Elemental' },
  { id: 72, radius: 16, sprite: 'KEEN', sequence: 'A', kind: ThingKind.monster, description: 'Commander Keen' },
  { id: 73, radius: 16, sprite: 'HDB1', sequence: 'A', kind: ThingKind.obstacle, description: 'Hanging victim, guts removed' },
  { id: 74, radius: 16, sprite: 'HDB2', sequence: 'A', kind: ThingKind.obstacle, isFloater: true, description: 'Hanging victim, guts and brain removed' },
  { id: 75, radius: 16, sprite: 'HDB3', sequence: 'A', kind: ThingKind.obstacle, isFloater: true, description: 'Hanging torso, looking down' },
  { id: 76, radius: 16, sprite: 'HDB4', sequence: 'A', kind: ThingKind.obstacle, isFloater: true, description: 'Hanging torso, open skull' },
  { id: 77, radius: 16, sprite: 'HDB5', sequence: 'A', kind: ThingKind.obstacle, isFloater: true, description: 'Hanging torso, looking up' },
  { id: 78, radius: 16, sprite: 'HDB6', sequence: 'A', kind: ThingKind.obstacle, isFloater: true, description: 'Hanging torso, brain removed' },
  { id: 79, radius: 16, sprite: 'POB1', sequence: 'A'	, description: 'Pool of blood' },
  { id: 80, radius: 16, sprite: 'POB2', sequence: 'A'	, description: 'Pool of blood' },
  { id: 81, radius: 16, sprite: 'BRS1', sequence: 'A'	, description: 'Pool of brains' },
  { id: 82, radius: 20, sprite: 'SGN2', sequence: 'A', kind: ThingKind.weapon, description: 'Super shotgun' },
  { id: 83, radius: 20, sprite: 'MEGA', sequence: 'ABCD', kind: ThingKind.artifact, description: 'Megasphere' },
  { id: 84, radius: 20, sprite: 'SSWV', kind: ThingKind.monster, description: 'Wolfenstein SS' },
  { id: 85, radius: 16, sprite: 'TLMP', sequence: 'ABCD', kind: ThingKind.obstacle, description: 'Tall techno floor lamp' },
  { id: 86, radius: 16, sprite: 'TLP2', sequence: 'ABCD', kind: ThingKind.obstacle, description: 'Short techno floor lamp' },
  { id: 87, radius: 0, description: 'Spawn spot' },
  { id: 88, radius: 16, sprite: 'BBRN', kind: ThingKind.obstacle, description: 'Boss Brain' },
  { id: 89, radius: 20, description: 'Spawn shooter' },
  { id: 2001, radius: 20, sprite: 'SHOT', sequence: 'A', kind: ThingKind.weapon, description: 'Shotgun' },
  { id: 2002, radius: 20, sprite: 'MGUN', sequence: 'A', kind: ThingKind.weapon, description: 'Chaingun' },
  { id: 2003, radius: 20, sprite: 'LAUN', sequence: 'A', kind: ThingKind.weapon, description: 'Rocket launcher' },
  { id: 2004, radius: 20, sprite: 'PLAS', sequence: 'A', kind: ThingKind.weapon, description: 'Plasma rifle' },
  { id: 2005, radius: 20, sprite: 'CSAW', sequence: 'A', kind: ThingKind.weapon, description: 'Chainsaw' },
  { id: 2006, radius: 20, sprite: 'BFUG', sequence: 'A', kind: ThingKind.weapon, description: 'BFG 9000' },
  { id: 2007, radius: 20, sprite: 'CLIP', sequence: 'A', kind: ThingKind.pickup, description: 'Ammo clip' },
  { id: 2008, radius: 20, sprite: 'SHEL', sequence: 'A', kind: ThingKind.pickup, description: 'Shotgun shells' },
  { id: 2010, radius: 20, sprite: 'ROCK', sequence: 'A', kind: ThingKind.pickup, description: 'Rocket' },
  { id: 2011, radius: 20, sprite: 'STIM', sequence: 'A', kind: ThingKind.pickup, description: 'Stimpack' },
  { id: 2012, radius: 20, sprite: 'MEDI', sequence: 'A', kind: ThingKind.pickup, description: 'Medikit' },
  { id: 2013, radius: 20, sprite: 'SOUL', sequence: 'ABCDCB', kind: ThingKind.artifact, description: 'Soul sphere' },
  { id: 2014, radius: 20, sprite: 'BON1', sequence: 'ABCDCB', kind: ThingKind.artifact, description: 'Health potion' },
  { id: 2015, radius: 20, sprite: 'BON2', sequence: 'ABCDCB', kind: ThingKind.artifact, description: 'Spiritual armor' },
  { id: 2018, radius: 20, sprite: 'ARM1', sequence: 'AB', kind: ThingKind.pickup, description: 'Green armor' },
  { id: 2019, radius: 20, sprite: 'ARM2', sequence: 'AB', kind: ThingKind.pickup, description: 'Blue armor' },
  { id: 2022, radius: 20, sprite: 'PINV', sequence: 'ABCD', kind: ThingKind.artifact, description: 'Invulnerability' },
  { id: 2023, radius: 20, sprite: 'PSTR', sequence: 'A', kind: ThingKind.artifact, description: 'Berserk' },
  { id: 2024, radius: 20, sprite: 'PINS', sequence: 'BCD', kind: ThingKind.artifact, description: 'Invisibility' },
  { id: 2025, radius: 20, sprite: 'SUIT', sequence: 'A', kind: ThingKind.pickup, description: 'Radiation suit' },
  { id: 2026, radius: 20, sprite: 'PMAP', sequence: 'ABCDCB', kind: ThingKind.artifact, description: 'Computer map' },
  { id: 2028, radius: 16, sprite: 'COLU', sequence: 'A', kind: ThingKind.obstacle, description: 'Floor lamp' },
  { id: 2035, radius: 10, sprite: 'BAR1', sequence: 'AB', kind: ThingKind.obstacle, description: 'Barrel' },
  { id: 2045, radius: 20, sprite: 'PVIS', sequence: 'AB', kind: ThingKind.artifact,	description: 'Light amplification visor' },
  { id: 2046, radius: 20, sprite: 'BROK', sequence: 'A', kind: ThingKind.pickup, description: 'Box of rockets' },
  { id: 2047, radius: 20, sprite: 'CELL', sequence: 'A', kind: ThingKind.pickup, description: 'Cell charge' },
  { id: 2048, radius: 20, sprite: 'AMMO', sequence: 'A', kind: ThingKind.pickup, description: 'Box of ammo' },
  { id: 2049, radius: 20, sprite: 'SBOX', sequence: 'A', kind: ThingKind.pickup, description: 'Box of shells' },
  { id: 3001, radius: 20, sprite: 'TROO', kind: ThingKind.monster, description: 'Imp' },
  { id: 3002, radius: 30, sprite: 'SARG', kind: ThingKind.monster, description: 'Demon' },
  { id: 3003, radius: 24, sprite: 'BOSS', kind: ThingKind.monster, description: 'Baron of Hell' },
  { id: 3004, radius: 20, sprite: 'POSS', kind: ThingKind.monster, description: 'Former Human Trooper' },
  { id: 3005, radius: 31, sprite: 'HEAD', kind: ThingKind.monster, isFloater: true, description: 'Cacodemon' },
  { id: 3006, radius: 16, sprite: 'SKUL', kind: ThingKind.monster, isFloater: true, description: 'Lost Soul'}  
];

export const thingTypesById = thingTypes.reduce<Record<number, ThingType>>((acc, thing) => {
  acc[thing.id] = thing;
  return acc;
}, {});


